name-map:
  REJECT: adblock
  PROXY: proxy
  è‡ªåŠ¨é€‰æ‹©: region
  DIRECT: direct

categories:
  redir:
    - "->"
    - ä¸­è½¬
    - OVERALL
  JP:
    - JP
    - Japan
    - æ—¥
    - ğŸ‡¯ğŸ‡µ
  US:
    - US
    - United States
    - ç¾
    - ğŸ‡ºğŸ‡¸
  CN:
    - CN
    - China
    - ä¸­å›½
    - ä¸Šæµ·
    - æµ™æ±Ÿ
    - å¹¿ä¸œ
    - æ·±åœ³
    - ğŸ‡¨ğŸ‡³
  HK:
    - HK
    - Hong Kong
    - æ¸¯
    - ğŸ‡­ğŸ‡°
  TW:
    - TW
    - Taiwan
    - å°
    - ğŸ‡¹ğŸ‡¼
  CA:
    - CA
    - Canada
    - åŠ æ‹¿å¤§
    - ğŸ‡¨ğŸ‡¦
  FR:
    - FR
    - French
    - æ³•
    - ğŸ‡«ğŸ‡·
  SG:
    - SG
    - Singapore
    - æ–°åŠ å¡
    - ç‹®åŸ
    - ğŸ‡¸ğŸ‡¬
  GB:
    - GB
    - UK
    - United Kindom
    - Britain
    - è‹±
    - ğŸ‡¬ğŸ‡§
  KR:
    - KR
    - Korea
    - éŸ©
    - ğŸ‡°ğŸ‡·
  RU:
    - RU
    - Russia
    - ä¿„
    - ğŸ‡·ğŸ‡º
  DE:
    - DE
    - Germany
    - å¾·
    - ğŸ‡©ğŸ‡ª
  SE:
    - SE
    - Sweden
    - ç‘å…¸
    - ğŸ‡¸ğŸ‡ª
  CH:
    - CH
    - Switzerland
    - ç‘å£«
    - ğŸ‡¨ğŸ‡­
  EE:
    - EE
    - Estonia
    - çˆ±æ²™å°¼äºš
    - ğŸ‡ªğŸ‡ª

categories_disp:
  HK: ğŸ‡­ğŸ‡° é¦™æ¸¯
